verif:
  project_name: "ecds_v1"
  by_step: "12h"
  fcst_model:
    - EC9
    - cca_dini25a_l90_arome_3dvar_v1
  lead_time: seq(0, 48, 3)
  fcst_type: "det"  #det or eps
  grps: "default"  #use default groupings of leadtime and fcst_cycle
  domains:  #what domains to verify ("All" will just consider all possible synops)
    - "All"
  members: #what members to verify for each ensemble. Include a list if the members differ between models. Set to NULL to use all available members in an ensemble
    - NULL
  lags: #how to lag the members for each ensemble. Include a list if the lags differ between models. Set to "0h" for no lagging
    - "0h"
  num_ref_members: #number of reference members to use when computing fair scores for an ensemble. Set to "NA" to not use this option (e.g. for a det run)
    - "NA"
  fcst_path: "/ec/res4/scratch/nhd/verification/DMI_data/FCTABLE"
  obs_path: "/ec/res4/scratch/nhd/verification/DMI_data/OBSTABLE/"
  verif_path: "/ec/res4/scratch/nhd/verification/rds_files"
pre:
  fcst_model:
    - EC9
  vfld_path: "/ec/res4/scratch/nhx/oprint" #"/ec/res4/scratch/nhd/verification/vfld"
  vfld_by: "1h"
  vfld_template:  #include one for each model if they are different
    - "vfld"
  vobs_path: "/ec/res4/scratch/nhd/verification/DMI_data/vobs"
  vobs_by: "1h"
  custom_asl_path: NULL
  members:  #include a list of members for each model if they are different
    - NULL
  lags: 
    - NULL
  params:
    - T2m
    - Tmax
    - Tmin
    - S10m
    - Gmax
    - Td2m
    - RH2m
    - Q2m
    - Pmsl
    - Pcp
    - CCtot
    - Cbase
    - vis
    - T
    - S
    - Td
post:
  plot_output: "/ec/res4/scratch/nhd/verification/plots"
  create_png: TRUE
scorecards:  # Not fully implemented in user scripts
  create_scrd: FALSE # Flag to run scorecard generation or not
  ref_model: EC9 
  fcst_model: cca_dini25a_l90_arome_3dvar_v1
  parameters: # Can be different from parameters in "set_params" file"
    - T2m
    - S10m
    - RH2m
    - Pmsl
  scores:
    - "bias"
    - "rmse"
  domains: # Construct scorecards for these domains only (must be in verif$domains)
    - "All"
  pooled_by: fcdate
  numboot: 100
  parallel: FALSE
  num_cores: 1
  plot_signif: TRUE # Plot the actual differnce between fcst_model and ref_model (and the confidence of that difference)
