#!/bin/bash
#PBS -v OMP_NUM_THREADS=1
#PBS -N conv2verif
#PBS -l pvmem=20gb
#PBS -o /data/cap/scripts
#PBS -j oe -W umask=022
#PBS -q gpc
#PBS -V
#PBS -l walltime=24:00:00
#PBS -N split12

export MPPEXEC=""
export MPPGL=""
export NPOOLS=1
export NPROC=1
ulimit -S -s unlimited || ulimit -s
ulimit -S -m unlimited || ulimit -m
ulimit -S -d unlimited || ulimit -d

WRKDIR=/home/cap/verify/scripts_verif
bash $WRKDIR/splitvobs_EC.sh 12 >& $WRKDIR/salida_split_12
