#some paths needed
coordinates_path: "/data/users/cap/glatmodel/processed_shadows/shadows_data.db"
heights_path: "/data/users/cap/glatmodel/data_shadows/all_heights.csv"
sql_dbs_path: "/data/projects/glatmodel/verification/harp"
fcst_path: "/data/projects/glatmodel/fcst/sql_dbs/"
obs_path: "/data/projects/glatmodel/obs/sql_dbs/"

